name: Developerspal
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8d9f6'
    - '#f7f7f7'
    - '#a2a2a2'
    - '#bde0f6'
    - '#a4b9c6'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
