name: Developerspal
favicon: null
layout_spectrum: 0.8794393024872988
typography_spectrum: 0.9526655753143132
title: Developerspal - We make development painless
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8d9f6'
    - '#f7f7f7'
    - '#a2a2a2'
    - '#bde0f6'
    - '#a4b9c6'
  brandStrength: 1
  lightness: 0.24326711148023605
  saturation: 0.025134798139333725
  rhythmicContrast: 0.2907105826307088
purpose: []
