analytics: {}
color:
  brandColors:
    - '#a8d9f6'
    - '#f7f7f7'
    - '#a2a2a2'
    - '#bde0f6'
    - '#a4b9c6'
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 1
name: Developerspal
opengraph: {}
purpose: []
typography_spectrum: 1
